config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :buildings, except: [:edit, :new, :show, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  include FilterByCoordinates # Концерн для поиска объектов, содержит метод и нужную информацию
  attr_accessor :house, :street, :seed # Нужны для формы
  validates :address, :latitude, :longitude, presence: true
  validates :house, :street, presence: true, unless: :seed?
  validate :there_any_coordinates? # Проверка на то что заполнены координаты

  before_validation :set_option

  private

  def set_option #Заполняем адресс и ищем у геокодера Яндекса
    return if seed?
    self.address = "Россия, Москва, #{street}, #{house}"
    coordinates = Geocoder.search(address, params: {kind: 'house', results: 1, lang: 'ru_RU', format: 'json'}).first.coordinates
    if coordinates.present?
      self.latitude = coordinates[0]
      self.longitude = coordinates[1]
    end
  end

  def there_any_coordinates?
    error.add(:house, 'Дом не найден') unless latitude.present? || longitude.present?
  end

  def seed?
    seed == '1'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, except: [:index, :create]

  def index
    @buildings = Building.filter_by_coordinates(params[:coordinates], params[:distance])
  end

  def create
    @building = Building.new(building_params)
    respond_to do |format|
      if @building.save
        format.json {render json: {message: 'Здание успешно добавлено'}, status: :ok }
      else
        format.json {render json: {data: @building.errors.messages, message: 'Ошибка'}, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @building.destroy
    respond_to do |format|
      format.json {render json: {message: 'Здание успешно удалено'}, status: :ok }
    end
  end

  private

  def building_params
    params.require(:building).permit(:house, :street)
  end

  def set_building
    @building = Building.find(params[:id])
  end

end

app/controllers/concerns/filter_by_coordinates.rb
module FilterByCoordinates
  extend ActiveSupport::Concern
  included do
    MOSCOW_COOR = [55.753595, 37.621031]
    INFO = {
        center_coordinates: MOSCOW_COOR,
        zoom: 13,
        distance: 4
    }
    reverse_geocoded_by :latitude, :longitude
  end

  module ClassMethods
    def filter_by_coordinates(coordinates, distance)
      coordinates = INFO[:center_coordinates] if coordinates.blank?
      distance = INFO[:distance] if distance.blank?
      near(coordinates, distance, latitude: :latitude, longitude: :longitude).reorder(:distance)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row" style="background: #61D7A4">
  <div class="col-md-12">
    <h1>Тестовое задание для Level travel.</h1>
    <p>Кликните на карту и получите объекты из базы данных в радиусе указанном ниже карты в текстовом поле.</p>
    <p>Если вы оставите поле пустым, поиск будет произведен в радиусе 4 км.</p>
    <p>Так же можно добавить или удалить адрес.</p>
  </div>
</div>

<div class="row">
  <%= hidden_field_tag :map_settings, '', data: {coordinates: Building::INFO[:center_coordinates], zoom: Building::INFO[:zoom]} %>
  <div id="map" class="cart-div"></div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render 'home/shared/table' %>
  </div>
</div>

app/views/home/shared/_create_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= simple_form_for Building.new, html: {id: 'building-form', data: {model: 'building'}} do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Добавить адрес</h4>
        </div>
        <div class="modal-body">
          <%= f.input :street, require: true, label: 'Улица' %>
          <%= f.input :house, require: true, label: 'Дом' %>
        </div>
        <div class="modal-footer">
          <%= link_to 'Добавить', '#', class: 'btn btn-success', id: 'submit-button' %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/shared/_table.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-8">
        <h3>Список зданий / адресов</h3>
      </div>
      <div class="col-md-4">
        <div class="row" style="margin-top: 20px">
          <div class="col-md-4">
            <%= text_field_tag :distance, params[:distance], class: 'form-control', placeholder: 'Радиус', id: 'radius' %>
          </div>
          <div class="col-md-8">
            <%= link_to 'Добавить адрес', '#', class: 'btn btn-default create-address btn-block', data: {toggle: 'modal', target: '#myModal'} %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-12">
        <table class="table" id="buildings-tables" data-url="<%= buildings_path %>">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Адрес</th>
            <th scope="col">Растояние, км</th>
            <th scope="col">Действия</th>
          </tr>
          </thead>
          <tbody id="table-body">
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render 'home/shared/create_modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Тестовое задание для Level travel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://api-maps.yandex.ru/2.1/?apikey=960cb057-bf0b-48ee-918f-e2bf63252d9c&lang=ru_RU" type="text/javascript"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <footer class="text-center" style="background: #007241">
      <br>
      <p>Тестовое задание для Level travel, версия: 0.0.1</p>
      <br>
    </footer>
  </body>
</html>